FROM python:3.12-slim

WORKDIR /app

# System dependencies for phoebe, matplotlib, etc.
RUN apt-get update && apt-get install -y \
    libfreetype6-dev libpng-dev libfontconfig1 curl \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY docker/requirements.api.txt .
RUN pip install --no-cache-dir -r requirements.api.txt

# Copy FastAPI app code
COPY api/ ./api

# Run Gunicorn + Uvicorn worker
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
